PWEB/Controllers/VehicleController.cs
using P.Domain.Entities;
using P.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PWEB.Controllers
{
    public class VehicleController : Controller
    {
        VehicleService vs = new VehicleService();
        UserService us = new UserService();
        FiscalPowerService fps = new FiscalPowerService();

        // GET: Vehicle
        public ActionResult Vehicles()
        {
            var vehicles = vs.GetAll();
            return View();
        }
        

        // GET: Vehicle/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Vehicle/Create
        public ActionResult Create()
        {
            var users = us.GetAll();          
            ViewBag.User = new SelectList(users, "IdUser", "Name");
            var fpowers = fps.GetAll();
            ViewBag.FiscalPower = new SelectList(fpowers, "IdFiscalPower", "FPower");

            return View();
        }

        // POST: Vehicle/Create
        [HttpPost]
        public ActionResult Create(Vehicle v, HttpPostedFileBase file)
        {
            
                vs.Add(v);
                vs.Commit();
                return RedirectToAction("Vehicles");
           
        }

        // GET: Vehicle/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Vehicle/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Vehicles");
            }
            catch
            {
                return View();
            }
        }

        // GET: Vehicle/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Vehicle/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Vehicles");
            }
            catch
            {
                return View();
            }
        }
    }
}

PWEB/Views/Vehicle/Create.cshtml
@model P.Domain.Entities.Vehicle

@{
    ViewBag.Title = "Create";
}


<h2>Create</h2>


@using (Html.BeginForm("Create", "Vehicle", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Vehicle</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Registration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Registration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Registration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SeatsNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SeatsNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SeatsNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ValueWhenNew, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ValueWhenNew, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ValueWhenNew, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ValueWhenVenal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ValueWhenVenal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ValueWhenVenal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InitTraficDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InitTraficDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InitTraficDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdUser, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdUser", (SelectList)ViewData["User"])
                @Html.ValidationMessageFor(model => model.IdUser, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdFiscalPower, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdFiscalPower", (SelectList)ViewData["FiscalPower"])
                @Html.ValidationMessageFor(model => model.IdFiscalPower, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PWEB/Views/Vehicle/Vehicles.cshtml
@model IEnumerable<P.Domain.Entities.Vehicle>

@{
    ViewBag.Title = "Vehicles";
}
@using (Html.BeginForm("Vehicles", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <label>Liste des véhicules</label> <input type="text" name="nbr" />
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Search" class="btn btn-default" />
        </div>
    </div>
}

<h2>Vehicles</h2>

@using (Html.BeginForm())
{
    <table>
        <tr>
            <td>
                <div>
                    Search by genre: @Html.TextBox("searchString")
                </div>
            </td>
            <td>
                <input type="submit" value="Search" id="submit" />
            </td>
        </tr>
    </table>
}

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Registration)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Brand)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SeatsNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ValueWhenNew)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ValueWhenVenal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.InitTraficDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdUser)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdFiscalPower)
        </th>
        <th></th>
    </tr>
    @if (Model != null) {
        foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Registration)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Brand)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SeatsNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ValueWhenNew)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ValueWhenVenal)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.InitTraficDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdUser)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdFiscalPower)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.IdVehicle }) |
            @Html.ActionLink("Details", "Details", new { id=item.IdVehicle }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.IdVehicle })
        </td>
    </tr>
    }
    }

</table>