PWEB/Controllers/FiscalPowerController.cs
using P.Domain.Entities;
using P.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PWEB.Controllers
{
    public class FiscalPowerController : Controller
    {
        FiscalPowerService fps = new FiscalPowerService();
        // GET: FiscalPower
        public ActionResult Index()
        {
            return View();
        }

        // GET: FiscalPower/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: FiscalPower/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FiscalPower/Create
        [HttpPost]
        public ActionResult Create(FiscalPower fp, HttpPostedFileBase file)
        {

            fps.Add(fp);
            fps.Commit();
            return RedirectToAction("Create");
           
        }

        // GET: FiscalPower/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: FiscalPower/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: FiscalPower/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: FiscalPower/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

PWEB/Views/FiscalPower/Create.cshtml
@model P.Domain.Entities.FiscalPower

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "FiscalPower", FormMethod.Post, new { enctype = "multipart/form-data" }))

{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>FiscalPower</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FPower, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FPower, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FPower, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}